import Link from "next/link";
import { cn } from "@/lib/cn";

const INDIGO = "#5b4fd1";
const AMBER = "#e58313";

// Generated by scripts/brand/build_logo.py — edit the spec there, not here.
const MARK_INDIGO =
  "M66.63 0L74.11 0A10.37 10.37 0 0 1 83.39 5.73L98.03 35.02A2.59 2.59 0 0 1 95.71 38.77L76.57 38.77A10.37 10.37 0 0 0 67.72 43.76L36.55 95.02A10.37 10.37 0 0 1 27.69 100L4.61 100A2.59 2.59 0 0 1 2.39 96.06L57.77 4.98A10.37 10.37 0 0 1 66.63 0Z";
const MARK_AMBER =
  "M82.3 59.36L102.83 59.36A10.37 10.37 0 0 1 112.11 65.09L127.69 96.25A2.59 2.59 0 0 1 125.37 100L104.83 100A10.37 10.37 0 0 1 95.56 94.27L79.98 63.11A2.59 2.59 0 0 1 82.3 59.36Z";
// The mark is 129.56 x 100; 5.5 units of padding keep `size` meaning the same
// visual size as the previous logo (mark ≈ 90% of the box height).
const PAD = 5.5;
const VB_W = 129.56 + PAD * 2;
const VB_H = 100 + PAD * 2;

/**
 * Agentronics logomark — the "A": an indigo apex cap + left leg with a
 * detached amber lower-right leg. True geometric vector (parallel edges, one
 * shared baseline, two-radius corners) measured from the brand master. Brand
 * colours are baked (this is the logo, not a themed surface), so it reads on
 * light and dark alike; `onDark` is accepted for API compatibility.
 */
export function Logomark({
  size = 26,
  onDark: _onDark = false,
  className,
}: {
  size?: number;
  onDark?: boolean;
  className?: string;
}) {
  return (
    <svg
      width={(size * VB_W) / VB_H}
      height={size}
      viewBox={`${-PAD} ${-PAD} ${VB_W} ${VB_H}`}
      fill="none"
      className={className}
      role="img"
      aria-label="Agentronics"
    >
      <path d={MARK_INDIGO} fill={INDIGO} />
      <path d={MARK_AMBER} fill={AMBER} />
    </svg>
  );
}

interface LogoProps {
  onDark?: boolean;
  href?: string;
  size?: number;
  showWordmark?: boolean;
  className?: string;
}

export function Logo({
  onDark = false,
  href = "/",
  size = 24,
  showWordmark = true,
  className,
}: LogoProps) {
  const content = (
    <span className={cn("inline-flex shrink-0 items-center gap-2 leading-none", className)}>
      <Logomark size={size} onDark={onDark} className="block shrink-0" />
      {showWordmark && (
        <span
          className={cn(
            "font-sans font-semibold text-[19px] leading-none tracking-tight whitespace-nowrap",
            onDark ? "text-white" : "text-content",
          )}
        >
          agentronics
        </span>
      )}
    </span>
  );

  return href ? (
    <Link href={href} className="focus-ring rounded-md" aria-label="Agentronics home">
      {content}
    </Link>
  ) : (
    content
  );
}
